name: task-manager-app-autodev-121
databases:
  - engine: PG
    name: db
    version: '14'
    production: false
    size: db-s-dev-database
ingress:
  rules:
    - component:
        name: web
      match:
        path:
          prefix: /
jobs:
  - name: db-migrate
    environment_slug: python
    envs:
      - key: FLASK_APP
        value: app.py
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: '${db.DATABASE_URL}'
      - key: SECRET_KEY
        value: '${SECRET_KEY}'
        type: SECRET
    git:
      branch: main
      repo_clone_url: 'https://github.com/digitalocean-labs/task-manager-app-autodev.git'
    source_dir: /
    run_command: flask db upgrade
services:
  - name: web
    environment_slug: python
    git:
      branch: main
      repo_clone_url: 'https://github.com/digitalocean-labs/task-manager-app-autodev.git'
    source_dir: /
    build_command: |
      pip install --upgrade pip
      pip install -r requirements.txt
    run_command: |
      gunicorn \
        --worker-class gevent \
        -w 1 \
        --bind 0.0.0.0:$PORT \
        "app:create_app()"
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /api/health
    envs:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: '8080'
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: '${db.DATABASE_URL}'
      - key: REDIS_URL
        value: 'redis://redis:6379'
      - key: SECRET_KEY
        value: '${SECRET_KEY}'
        type: SECRET
      - key: JWT_SECRET_KEY
        value: '${JWT_SECRET_KEY}'
        type: SECRET
      - key: MAIL_PASSWORD
        value: '${MAIL_PASSWORD}'
        type: SECRET
      - key: MAIL_SERVER
        value: '${MAIL_SERVER}'
      - key: MAIL_PORT
        value: '${MAIL_PORT}'
      - key: MAIL_USERNAME
        value: '${MAIL_USERNAME}'
      - key: DO_API_TOKEN
        value: '${DO_API_TOKEN}'
        type: SECRET
workers:
  - name: redis
    image:
      registry_type: DOCKER_HUB
      repository: redis
      tag: 7-alpine
    instance_count: 1
    instance_size_slug: basic-xxs
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DEPLOYMENT_LIVE