
  name: task-manager-app-226

  databases:
    - engine: PG
      name: db
      version: "14"
      production: false
      size: db-s-dev-database

  ingress:
    rules:
      - component:
          name: web
        match:
          path:
            prefix: /

  services:
    - name: web
      environment_slug: python
      source_dir: /
      instance_count: 1
      instance_size_slug: basic-xxs
      git:
        repo_clone_url: https://github.com/digitalocean-labs/task-manager-app-autodev.git
        branch: main

      build_command: |
        pip install --upgrade pip
        pip install -r requirements.txt

      run_command: |
        gunicorn \
          --worker-class eventlet \
          --workers 1 \
          --bind 0.0.0.0:$PORT \
            app_socketio:app
      http_port: 8080    
      health_check:
        http_path: /api/health

      envs:
        - key: FLASK_APP
          value: app_socketio.py

        - key: FLASK_ENV
          value: production

        - key: DATABASE_URL
          scope: RUN_AND_BUILD_TIME
          value: ${db.DATABASE_URL}

        - key: REDIS_URL
          value: ${REDIS_URL}

        - key: SECRET_KEY
          value: ${SECRET_KEY}
          type: SECRET

        - key: JWT_SECRET_KEY
          value: ${JWT_SECRET_KEY}
          type: SECRET

        - key: MAIL_SERVER
          value: ${MAIL_SERVER}

        - key: MAIL_PORT
          value: ${MAIL_PORT}

        - key: MAIL_USERNAME
          value: ${MAIL_USERNAME}

        - key: MAIL_PASSWORD
          value: ${MAIL_PASSWORD}
          type: SECRET

  jobs:
    - name: db-migrate
      kind: PRE_DEPLOY
      environment_slug: python
      source_dir: /

      git:
        repo_clone_url: https://github.com/digitalocean-labs/task-manager-app-autodev.git
        branch: main

      build_command: |
        pip install --upgrade pip
        pip install -r requirements.txt

      run_command: |
        flask db upgrade

      envs:
        - key: FLASK_APP
          value: app_socketio.py

        - key: DATABASE_URL
          scope: RUN_TIME
          value: ${db.DATABASE_URL}

        - key: SECRET_KEY
          value: ${SECRET_KEY}
          type: SECRET

  workers:
    - name: redis
      image:
        registry_type: DOCKER_HUB
        repository: redis
        tag: "7-alpine"
      instance_count: 1
      instance_size_slug: basic-xxs

  alerts:
    - rule: DEPLOYMENT_FAILED
    - rule: DEPLOYMENT_LIVE